#!/usr/bin/env bash
clear && sleep 4 && \
echo " Running provision for qemu environment "
sleep 2 && \
apt-get update && apt-get -f install -y && apt-get upgrade -y && apt-get -f install -y && \
#@ Needs to be orig /boot -> do from qbian ??
echo "Editing /boot/config.txt - note device is required" && \
echo -e "dtparam=i2c1=on\ndtparam=i2c_arm=on\ndevice_tree=" >> /boot/config.txt && \
rpi-serial-console disable && \
echo "Complete" && sleep 2 && reboot
