#!/usr/bin/env bash
clear && sleep 4 && \
# Only upgrade when on device so that /boot can be updated & upgraded.
# Note that pi /boot dir doesn't get mounted the same in the emulator compared to the device
echo " Running provision for qemu environment "
sleep 2 && \
apt-get update && apt-get -f install -y && apt-get upgrade -y && apt-get -f install -y && \
#@ Needs to be orig /boot -> do from qbian ??
echo "Editing /boot/config.txt - note device is required" && \
echo -e "dtparam=i2c1=on\ndtparam=i2c_arm=on\ndevice_tree=" >> /boot/config.txt && \
/root/rpi-serial-console/rpi-serial-console disable && \
echo "Complete Device Provisions"
