#!/usr/bin/env bash
PWD=$(pwd)
FOLDER=$2

function create(){
  mkdir $PWD/$FOLDER && rsync -avz $BASE/Provision/InitSkel/* $PWD/$FOLDER && \
  mv $PWD/$FOLDER/Qbian $PWD/$FOLDER/.Qbian && mv $PWD/$FOLDER/gitignore $PWD/$FOLDER/.gitignore
  exit 0
}

if [ ! -z $FOLDER ] && [ ! -d $PWD/$FOLDER ];then
  create
else
  if [ -d $PWD/$FOLDER ] && [ ! -z $FOLDER ];then
    echo "\"$FOLDER\" already available. Cannot overwrite."
    exit 1
  else
    echo "Params required. $ $package init <package-name>"
    exit 1
  fi
fi
