#!/usr/bin/env bash
echo " Running provision for qemu environment "

#@ Needs to be orig /boot -> do from qbian ??
echo "Editing /boot/config.txt - note device is required" && \
echo -e "dtparam=i2c1=on\ndtparam=i2c_arm=on\ntree=off" >> /boot/config.txt
