#!/usr/bin/env bash

ssh-keygen -t rsa -f $SSH/id_rsa -N "" -C "$user@$hostname" && \
cat $SSH/id_rsa.pub > $SSH/authorized_keys && \
if [ -f ~/.ssh/id_rsa.pub ] && [ "$useMySSH" == true ];then
  # insert the home ssh public key
  cat ~/.ssh/id_rsa.pub >> $SSH/authorized_keys
fi
export DEFAULT_IMG=true && \
$BASE/bin/qbian --create-img default "" 538M
